language: generic

cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    - ~/.cache

services:
  - docker

before_script:
  - docker-compose up -d --build
  - docker-compose -f pre-commit.yml build
  - docker-compose -f docker-compose-e2e.yml build cy-run

script:
  - docker-compose -f pre-commit.yml up
  - docker-compose exec backend ./coverage.sh
  - docker-compose exec frontend npm run lint
  - docker-compose -f docker-compose-e2e.yml run cy-run

after_script:
  - bash <(curl -s https://codecov.io/bash) -f backend/coverage.xml
  - bash <(curl -s https://codecov.io/bash) -f frontend/coverage/coverage-final.json
  - docker-compose down -v
