version: '3.7'

services:
  e2e:
    build:
      context: ./frontend
      dockerfile: Dockerfile.cy-open
    image: docker.pkg.github.com/ajithpmohan/image-gallery-app/e2e-testing-dev:0.3
    container_name: IG-e2e-testing
    # note: inside e2e-testing container, the network allows accessing
    # "frontend" host under name "localhost:9001"
    # so "curl http://localhost:9001" would return whatever the webserver
    # in the "frontend" container is cooking
    # see https://docs.docker.com/compose/networking/
    environment:
      - CYPRESS_baseUrl=http://localhost:9001
      - DISPLAY=unix${DISPLAY}
    command: npx cypress open --browser chrome
    network_mode: 'host'
    tty: true
    # mount the host directory frontend/cypress and the file frontend/cypress.json as
    # volumes within the container
    # this means that:
    #  1. anything that Cypress writes to these folders (e.g., screenshots,
    #     videos) appears also on the Docker host's filesystem
    #  2. any change that the developer applies to Cypress files on the host
    #     machine immediately takes effect within the e2e-testing container (no docker
    #     rebuild required).
    volumes:
      - ./frontend/cypress:/usr/src/app/frontend/cypress
      - ./frontend/cypress.json:/usr/src/app/frontend/cypress.json
      - ./frontend/coverage:/usr/src/app/frontend/coverage
      - /tmp/.X11-unix:/tmp/.X11-unix
