version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: docker.pkg.github.com/ajithpmohan/image-gallery-app/frontend-prod:1.0
    ports:
      - 1338:80
    depends_on:
      - backend
    env_file:
      # Before running the production yml file you need to copy
      # `frontend/.env.production.example` file to .env.production
      # and make appropriate changes.
      - ./frontend/.env.production
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: docker.pkg.github.com/ajithpmohan/image-gallery-app/backend-prod:1.0
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      # Before running the production yml file you need to copy
      # `backend/.env.prod.example` file to .env.prod and make
      # appropriate changes.
      - ./backend/.env.prod
  nginx-proxy:
    build: nginx
    image: docker.pkg.github.com/ajithpmohan/image-gallery-app/nginx-proxy:latest
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - backend
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - nginx/.env.prod.proxy-companion
    volumes:
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy

volumes:
  certs:
  html:
  vhost:
