version: '3.7'

services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ig_db
      - POSTGRES_USER=ig_user
      - POSTGRES_PASSWORD=ig_pwd
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: docker.pkg.github.com/ajithpmohan/image-gallery-app/frontend-prod:1.0
    ports:
      - 1338:80
    depends_on:
      - db
      - backend
    env_file:
      # Before running the production yml file you need to create `.env.production` file
      # inside frontend directory, which is excluded from git repository.
      # Check ./frontend/.env.development for reference. Otherwise app won't work properly.
      - ./frontend/.env.production
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: docker.pkg.github.com/ajithpmohan/image-gallery-app/backend-prod:1.0
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/assets/staticfiles
      - media_volume:/usr/src/app/assets/mediafiles
    expose:
      - 8000
    env_file:
      # Before running the production yml file you need to create `.env.prod` file
      # inside backend directory, which is excluded from git repository.
      # Check ./backend/.env.dev for reference. Otherwise app won't work properly.
      - ./backend/.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    image: docker.pkg.github.com/ajithpmohan/image-gallery-app/nginx-prod:1.0
    volumes:
      - static_volume:/usr/src/app/assets/staticfiles
      - media_volume:/usr/src/app/assets/mediafiles
    ports:
      - 1337:80
    depends_on:
      - backend
volumes:
  postgres-data:
  static_volume:
  media_volume:
