# Generated by Django 3.1.3 on 2020-11-25 14:43

from django.db import migrations, models
import django.db.models.deletion
import restapi.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Image Category', max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image Category',
                'verbose_name_plural': 'Image Categories',
                'db_table': 'image_category',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=restapi.utils.default_image_path, verbose_name='Image')),
                ('category', models.ForeignKey(blank=True, help_text='Image Category is not a mandatory field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagegallery', to='restapi.imagecategory')),
            ],
            options={
                'verbose_name': 'Image Gallery',
                'verbose_name_plural': 'Image Galleries',
                'db_table': 'image_gallery',
                'ordering': ['-category', '-created'],
            },
        ),
    ]
